name = "QSM"
uuid = "794fc106-2fa4-440f-961c-0d7d7b47016a"
authors = ["kamesy <ckames@physics.ubc.ca>"]
version = "0.4.1"

[deps]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastPow = "c0e83750-1142-43a8-81cf-6c956b72b4d1"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NIfTI = "a3a9e032-41b5-5fc4-967a-a6b7a19844d3"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PolyesterWeave = "1d0040c9-8b98-4ee7-8388-3f51789ca0ad"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SLEEFPirates = "476501e8-09a2-5ece-8869-fb82de89a1fa"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreadingUtilities = "8290d209-cae3-49c0-8002-c8c24d57dab5"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[compat]
CPUSummary = "0.1.23"
FFTW = "1.5.0"
FastPow = "0.1.0"
IrrationalConstants = "0.1.0"
LinearMaps = "3.6.1"
MacroTools = "0.5.6"
NIfTI = "0.5.7"
Polyester = "0.6.14"
PolyesterWeave = "0.1.7"
SLEEFPirates = "0.6.31"
Static = "0.7.6"
StaticArrays = "1"
ThreadingUtilities = "0.5.0"
TiledIteration = "0.3.1"
julia = "1.6"
